version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"

  testa:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A friendly hi"
  testb:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Salut"
      
      
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      
      

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - testa:
          requires:
            - build
      - testb:
          requires:
            - build
      - deploy:
          requires:
            - testa
            - testb
